### PR TITLE
multiple test fixes

### LINKED ISSUE #5573: State 'survivor' not found in RSI: '/Textures/_RMC14/Markers/landmarks.rsi'
linter fails because of it

### PR DESCRIPTION
**Pull request by Ian321**
## About the PR

This PR fixes some tests.

## Why / Balance

- fixes #5573
- fixes SpawnAndDirtyAllEntities
- fixes the AllItemsHaveSpritesTest
- fixes the PrototypeTests
- fixes the AllMapsTested
- fixes the ItemThrowingTest
- fixes the SpawnAndDeleteEntityCountTest
- fixes "Trying to set unregistered variable"
- fixes all YAML issues

## Technical details

- made the survivor jobs use the previously used cm_jobs RSI
  - same for the ASO spawn point
  - I even checked the SS13 DMI, there are no landmarks for survivors or the ASO.
  - added TODO comments so that someone hopefully creates those sprites
- RMCAttachmentM54CStockSolidMarksman has no camouflage variants
- OrbitalCannonExplosion.Type is nullable
- made RMCIntelBase and CMBaseWeaponRifle abstract
- Savannah is a real map
- Throwing items plays a animation that requires a sprite
- Gave spawners the "Spawner" category.
- removed ic.role_time and ic.kill_crit (they are in [ghost])
- Added missing slash and ProvostProvost

## Media

Screenshot From 2025-02-12 03-05-31

## Requirements

- [x] I have read and am following the [Pull Request and Changelog Guidelines](https://docs.spacestation14.com/en/general-development/codebase-info/pull-request-guidelines.html).
- [x] I have added media to this PR or it does not require an ingame showcase.
- [x] By submitting this code and/or assets, I confirm that I either own them or have provided the correct necessary licenses to use and distribute them. I agree to be fully responsible for any legal claims or issues arising from the use of these materials.

**Changelog**

No cl

### CODE REVIEW

**Comment by Ian321** [comment]
Looks like there are more things to fix...

<details>
<summary></summary>
I really need a new CPU. I still got a first generation AMD ryzen. It takes like 15 minutes to run all the tests and my PC actually crashed last time.
</details>

**Comment by Ian321** [comment]
OK, so for anyone wondering: The free GitHub runner has a hard memory limit of 16GB. `dotnet test` takes up to 30GB of ram if the tests inside `EntityTest` where allowed to run in parallel.

File: Content.IntegrationTests/Tests/EntityTest.cs [hunk 1]
```diff
@@ -14,6 +14,7 @@ namespace Content.IntegrationTests.Tests
 {
     [TestFixture]
     [TestOf(typeof(EntityUid))]
+    [NonParallelizable] // RMC14: We have some many entities that this causes a OOM.
```
Comment (DrSmugleaf) [inline Content.IntegrationTests/Tests/EntityTest.cs:17]: I was trying to find this for a while but couldn't figure it out, ty

**Review by DrSmugleaf — APPROVED** [review]
Thanks for the PR!
